### ISSUE TITLE
Failed to connect to localhost port 11434

### ISSUE THREAD

**Issue by segunolamidegitup** [ArdaGnsrn/ollama-php#1]
I got error below

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to 172.100.0.36 port 11434: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://172.100.0.36:11434/api/generate in

* Failed to connect to localhost port 11434 after 12 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to localhost port 11434 after 12 ms: Couldn't connect to server

**Comment by ArdaGnsrn** [comment]
You need to install Ollama on your server/computer. During installation or configuration, you should specify the port as 11434 if it is not set by default.

Once Ollama is installed, you need to start it.

**Install Ollama:** [https://ollama.com/download](https://ollama.com/download)

**Comment by segunolamidegitup** [comment]
Thanks
